# Generated by Django 4.1.7 on 2023-03-22 15:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_remove_password_secret_alter_password_algo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
