# Generated by Django 4.1.7 on 2023-03-22 15:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_password_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password',
            name='id',
        ),
        migrations.AlterField(
            model_name='password',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
