# Generated by Django 4.1.7 on 2023-03-22 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_remove_password_id_alter_password_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='uuid',
            new_name='id',
        ),
    ]
